spring:
  profiles:
    active:
    - dev
    
---
server:
  port: 4002
      defaultZone: http://eureka-test.com:7001/eureka/    
---
server:
  port: 4001
spring:
  profiles: dev
  application:
    name: QIQIHAL-config-client
eureka:
  client:
    service-url:
      defaultZone: http://eureka-dev.com:7001/eureka/    
    
 