spring:
  profiles:
    active:
    - test
---
server:
  port: 4001
spring:
  profiles: dev
  application:
    name: QIQIHAL-config-client
eureka:
  client:
    service-url:
      defaultZone: http://eureka-dev.com:7001/eureka/    
---
server:
  port: 4003
spring:
  profiles: test
  application:
    name: QIQIHAL-config-client
eureka:
  client:
    service-url:
      defaultZone: http://eureka-dev.com:7001/eureka/    
---      